#!/bin/sh

# Script for running miniJava compiler tests. 
# (For CS321 Language and Compiler Design, Portland State University.)
#
# Usage:
#   ./run tst/test01.in  -- test a single input
#   ./run tst/test*.in   -- test all inputs
#
# The script will compare your parser's output with a ref file (if exists),
# and save the diffs in a .diff file.
#

for i
do
	d=`dirname $i`
	f=`basename $i .in`
	echo -n "$d/$f: "
	java mjLexer $d/$f.in 1> $d/$f.out
	if [ -r $d/$f.out.ref ]; then
          diff -w $d/$f.out $d/$f.out.ref > $d/$f.out.diff; 
          if [ -s $d/$f.out.diff ]; then 
            echo "differs from ref (see $f.out.diff)"; 
          else
	    rm $d/$f.out.diff; 
            echo "matches ref"; 
          fi
	else
            echo "no ref to compare"; 
        fi
done
exit 0
