/* Generated By:JavaCC: Do not edit this line. AstParserTokenManager.java */
import java.util.*;
import java.io.*;
import ast.*;

/** Token Manager. */
public class AstParserTokenManager implements AstParserConstants
{

  /** Debug output. */
  public static  java.io.PrintStream debugStream = System.out;
  /** Set debug output. */
  public static  void setDebugStream(java.io.PrintStream ds) { debugStream = ds; }
private static final int jjStopStringLiteralDfa_0(int pos, long active0, long active1)
{
   switch (pos)
   {
      case 0:
         if ((active0 & 0x7ffffffff80L) != 0L)
         {
            jjmatchedKind = 48;
            return 18;
         }
         return -1;
      case 1:
         if ((active0 & 0x7fffffdff80L) != 0L)
         {
            jjmatchedKind = 48;
            jjmatchedPos = 1;
            return 18;
         }
         if ((active0 & 0x20000L) != 0L)
            return 18;
         return -1;
      case 2:
         if ((active0 & 0x14004008000L) != 0L)
            return 18;
         if ((active0 & 0x6bffbfd7f80L) != 0L)
         {
            if (jjmatchedPos != 2)
            {
               jjmatchedKind = 48;
               jjmatchedPos = 2;
            }
            return 18;
         }
         return -1;
      case 3:
         if ((active0 & 0x7cbfb987780L) != 0L)
         {
            if (jjmatchedPos != 3)
            {
               jjmatchedKind = 48;
               jjmatchedPos = 3;
            }
            return 18;
         }
         if ((active0 & 0x3400650800L) != 0L)
            return 18;
         return -1;
      case 4:
         if ((active0 & 0x347f3107700L) != 0L)
         {
            jjmatchedKind = 48;
            jjmatchedPos = 4;
            return 18;
         }
         if ((active0 & 0x48808880080L) != 0L)
            return 18;
         return -1;
      case 5:
         if ((active0 & 0x4203102600L) != 0L)
            return 18;
         if ((active0 & 0x305f0005100L) != 0L)
         {
            jjmatchedKind = 48;
            jjmatchedPos = 5;
            return 18;
         }
         return -1;
      case 6:
         if ((active0 & 0xc0001100L) != 0L)
            return 18;
         if ((active0 & 0x30530004000L) != 0L)
         {
            jjmatchedKind = 48;
            jjmatchedPos = 6;
            return 18;
         }
         return -1;
      case 7:
         if ((active0 & 0x130000000L) != 0L)
         {
            jjmatchedKind = 48;
            jjmatchedPos = 7;
            return 18;
         }
         if ((active0 & 0x30400004000L) != 0L)
            return 18;
         return -1;
      case 8:
         if ((active0 & 0x110000000L) != 0L)
            return 18;
         if ((active0 & 0x20000000L) != 0L)
         {
            jjmatchedKind = 48;
            jjmatchedPos = 8;
            return 18;
         }
         return -1;
      default :
         return -1;
   }
}
private static final int jjStartNfa_0(int pos, long active0, long active1)
{
   return jjMoveNfa_0(jjStopStringLiteralDfa_0(pos, active0, active1), pos + 1);
}
static private int jjStopAtPos(int pos, int kind)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   return pos + 1;
}
static private int jjMoveStringLiteralDfa0_0()
{
   switch(curChar)
   {
      case 33:
         jjmatchedKind = 65;
         return jjMoveStringLiteralDfa1_0(0x1000000000000000L, 0x0L);
      case 38:
         return jjMoveStringLiteralDfa1_0(0x200000000000000L, 0x0L);
      case 40:
         return jjStopAtPos(0, 49);
      case 41:
         return jjStopAtPos(0, 50);
      case 42:
         return jjStopAtPos(0, 55);
      case 43:
         return jjStopAtPos(0, 53);
      case 45:
         return jjStopAtPos(0, 54);
      case 47:
         return jjStopAtPos(0, 56);
      case 60:
         jjmatchedKind = 61;
         return jjMoveStringLiteralDfa1_0(0x4000000000000000L, 0x0L);
      case 61:
         return jjMoveStringLiteralDfa1_0(0x800000000000000L, 0x0L);
      case 62:
         jjmatchedKind = 63;
         return jjMoveStringLiteralDfa1_0(0x0L, 0x1L);
      case 65:
         return jjMoveStringLiteralDfa1_0(0x20300000000L, 0x0L);
      case 66:
         return jjMoveStringLiteralDfa1_0(0x800004000L, 0x0L);
      case 67:
         return jjMoveStringLiteralDfa1_0(0x2410000000L, 0x0L);
      case 68:
         return jjMoveStringLiteralDfa1_0(0x2000L, 0x0L);
      case 69:
         return jjMoveStringLiteralDfa1_0(0x40100L, 0x0L);
      case 70:
         return jjMoveStringLiteralDfa1_0(0x8000800000L, 0x0L);
      case 73:
         return jjMoveStringLiteralDfa1_0(0x21000L, 0x0L);
      case 77:
         return jjMoveStringLiteralDfa1_0(0x20200000L, 0x0L);
      case 78:
         return jjMoveStringLiteralDfa1_0(0x14000008000L, 0x0L);
      case 79:
         return jjMoveStringLiteralDfa1_0(0x84000000L, 0x0L);
      case 80:
         return jjMoveStringLiteralDfa1_0(0x40008000400L, 0x0L);
      case 82:
         return jjMoveStringLiteralDfa1_0(0x100000L, 0x0L);
      case 83:
         return jjMoveStringLiteralDfa1_0(0x3000200L, 0x0L);
      case 84:
         return jjMoveStringLiteralDfa1_0(0x410000L, 0x0L);
      case 85:
         return jjMoveStringLiteralDfa1_0(0x1000000000L, 0x0L);
      case 86:
         return jjMoveStringLiteralDfa1_0(0x40000000L, 0x0L);
      case 87:
         return jjMoveStringLiteralDfa1_0(0x80000L, 0x0L);
      case 99:
         return jjMoveStringLiteralDfa1_0(0x80L, 0x0L);
      case 118:
         return jjMoveStringLiteralDfa1_0(0x800L, 0x0L);
      case 123:
         return jjStopAtPos(0, 51);
      case 124:
         return jjMoveStringLiteralDfa1_0(0x400000000000000L, 0x0L);
      case 125:
         return jjStopAtPos(0, 52);
      default :
         return jjMoveNfa_0(0, 0);
   }
}
static private int jjMoveStringLiteralDfa1_0(long active0, long active1)
{
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(0, active0, active1);
      return 1;
   }
   switch(curChar)
   {
      case 38:
         if ((active0 & 0x200000000000000L) != 0L)
            return jjStopAtPos(1, 57);
         break;
      case 61:
         if ((active0 & 0x800000000000000L) != 0L)
            return jjStopAtPos(1, 59);
         else if ((active0 & 0x1000000000000000L) != 0L)
            return jjStopAtPos(1, 60);
         else if ((active0 & 0x4000000000000000L) != 0L)
            return jjStopAtPos(1, 62);
         else if ((active1 & 0x1L) != 0L)
            return jjStopAtPos(1, 64);
         break;
      case 97:
         return jjMoveStringLiteralDfa2_0(active0, 0x42440a00000L, active1, 0L);
      case 98:
         return jjMoveStringLiteralDfa2_0(active0, 0x80000000L, active1, 0L);
      case 101:
         return jjMoveStringLiteralDfa2_0(active0, 0x14020108000L, active1, 0L);
      case 102:
         if ((active0 & 0x20000L) != 0L)
            return jjStartNfaWithStates_0(1, 17, 18);
         break;
      case 104:
         return jjMoveStringLiteralDfa2_0(active0, 0x90000L, active1, 0L);
      case 105:
         return jjMoveStringLiteralDfa2_0(active0, 0x8800000000L, active1, 0L);
      case 108:
         return jjMoveStringLiteralDfa2_0(active0, 0x10040080L, active1, 0L);
      case 110:
         return jjMoveStringLiteralDfa2_0(active0, 0x1000001000L, active1, 0L);
      case 111:
         return jjMoveStringLiteralDfa2_0(active0, 0x6800L, active1, 0L);
      case 114:
         return jjMoveStringLiteralDfa2_0(active0, 0x20108400000L, active1, 0L);
      case 115:
         return jjMoveStringLiteralDfa2_0(active0, 0x200000000L, active1, 0L);
      case 116:
         return jjMoveStringLiteralDfa2_0(active0, 0x1000200L, active1, 0L);
      case 117:
         return jjMoveStringLiteralDfa2_0(active0, 0x4000400L, active1, 0L);
      case 120:
         return jjMoveStringLiteralDfa2_0(active0, 0x100L, active1, 0L);
      case 121:
         return jjMoveStringLiteralDfa2_0(active0, 0x2000000L, active1, 0L);
      case 124:
         if ((active0 & 0x400000000000000L) != 0L)
            return jjStopAtPos(1, 58);
         break;
      default :
         break;
   }
   return jjStartNfa_0(0, active0, active1);
}
static private int jjMoveStringLiteralDfa2_0(long old0, long active0, long old1, long active1)
{
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(0, old0, old1);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(1, active0, 0L);
      return 2;
   }
   switch(curChar)
   {
      case 97:
         return jjMoveStringLiteralDfa3_0(active0, 0x10000280L);
      case 98:
         return jjMoveStringLiteralDfa3_0(active0, 0x400L);
      case 101:
         return jjMoveStringLiteralDfa3_0(active0, 0x8000000000L);
      case 105:
         return jjMoveStringLiteralDfa3_0(active0, 0x8290800L);
      case 106:
         return jjMoveStringLiteralDfa3_0(active0, 0x80000000L);
      case 108:
         return jjMoveStringLiteralDfa3_0(active0, 0x2400800000L);
      case 110:
         return jjMoveStringLiteralDfa3_0(active0, 0x800000000L);
      case 111:
         return jjMoveStringLiteralDfa3_0(active0, 0x1000004000L);
      case 114:
         return jjMoveStringLiteralDfa3_0(active0, 0x60141000000L);
      case 115:
         return jjMoveStringLiteralDfa3_0(active0, 0x202040000L);
      case 116:
         if ((active0 & 0x4000000L) != 0L)
            return jjStartNfaWithStates_0(2, 26, 18);
         return jjMoveStringLiteralDfa3_0(active0, 0x20101100L);
      case 117:
         return jjMoveStringLiteralDfa3_0(active0, 0x402000L);
      case 119:
         if ((active0 & 0x8000L) != 0L)
         {
            jjmatchedKind = 15;
            jjmatchedPos = 2;
         }
         return jjMoveStringLiteralDfa3_0(active0, 0x14000000000L);
      default :
         break;
   }
   return jjStartNfa_0(1, active0, 0L);
}
static private int jjMoveStringLiteralDfa3_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(1, old0, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(2, active0, 0L);
      return 3;
   }
   switch(curChar)
   {
      case 65:
         return jjMoveStringLiteralDfa4_0(active0, 0x10000000000L);
      case 68:
         return jjMoveStringLiteralDfa4_0(active0, 0x40000000L);
      case 79:
         return jjMoveStringLiteralDfa4_0(active0, 0x4000000000L);
      case 84:
         return jjMoveStringLiteralDfa4_0(active0, 0x80001000L);
      case 97:
         return jjMoveStringLiteralDfa4_0(active0, 0x60100000000L);
      case 98:
         return jjMoveStringLiteralDfa4_0(active0, 0x2000L);
      case 100:
         if ((active0 & 0x800L) != 0L)
            return jjStartNfaWithStates_0(3, 11, 18);
         break;
      case 101:
         if ((active0 & 0x40000L) != 0L)
            return jjStartNfaWithStates_0(3, 18, 18);
         else if ((active0 & 0x400000L) != 0L)
            return jjStartNfaWithStates_0(3, 22, 18);
         return jjMoveStringLiteralDfa4_0(active0, 0x100L);
      case 104:
         return jjMoveStringLiteralDfa4_0(active0, 0x20000000L);
      case 105:
         return jjMoveStringLiteralDfa4_0(active0, 0x201000000L);
      case 108:
         if ((active0 & 0x2000000000L) != 0L)
         {
            jjmatchedKind = 37;
            jjmatchedPos = 3;
         }
         return jjMoveStringLiteralDfa4_0(active0, 0x8400084400L);
      case 110:
         if ((active0 & 0x200000L) != 0L)
            return jjStartNfaWithStates_0(3, 21, 18);
         return jjMoveStringLiteralDfa4_0(active0, 0x8000000L);
      case 111:
         return jjMoveStringLiteralDfa4_0(active0, 0x800000000L);
      case 112:
         if ((active0 & 0x1000000000L) != 0L)
            return jjStartNfaWithStates_0(3, 36, 18);
         break;
      case 115:
         if ((active0 & 0x10000L) != 0L)
            return jjStartNfaWithStates_0(3, 16, 18);
         return jjMoveStringLiteralDfa4_0(active0, 0x10800080L);
      case 116:
         return jjMoveStringLiteralDfa4_0(active0, 0x2000200L);
      case 117:
         return jjMoveStringLiteralDfa4_0(active0, 0x100000L);
      default :
         break;
   }
   return jjStartNfa_0(2, active0, 0L);
}
static private int jjMoveStringLiteralDfa4_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(2, old0, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(3, active0, 0L);
      return 4;
   }
   switch(curChar)
   {
      case 83:
         return jjMoveStringLiteralDfa5_0(active0, 0x400000000L);
      case 84:
         return jjMoveStringLiteralDfa5_0(active0, 0x4000L);
      case 98:
         return jjMoveStringLiteralDfa5_0(active0, 0x4000000000L);
      case 100:
         if ((active0 & 0x8000000000L) != 0L)
            return jjStartNfaWithStates_0(4, 39, 18);
         break;
      case 101:
         if ((active0 & 0x80000L) != 0L)
            return jjStartNfaWithStates_0(4, 19, 18);
         else if ((active0 & 0x800000L) != 0L)
            return jjStartNfaWithStates_0(4, 23, 18);
         return jjMoveStringLiteralDfa5_0(active0, 0x42000000L);
      case 103:
         return jjMoveStringLiteralDfa5_0(active0, 0x200000000L);
      case 105:
         return jjMoveStringLiteralDfa5_0(active0, 0x600L);
      case 108:
         return jjMoveStringLiteralDfa5_0(active0, 0x2000L);
      case 109:
         if ((active0 & 0x40000000000L) != 0L)
            return jjStartNfaWithStates_0(4, 42, 18);
         break;
      case 110:
         return jjMoveStringLiteralDfa5_0(active0, 0x1000100L);
      case 111:
         return jjMoveStringLiteralDfa5_0(active0, 0x20000000L);
      case 112:
         if ((active0 & 0x800000000L) != 0L)
            return jjStartNfaWithStates_0(4, 35, 18);
         break;
      case 114:
         return jjMoveStringLiteralDfa5_0(active0, 0x10000100000L);
      case 115:
         if ((active0 & 0x80L) != 0L)
            return jjStartNfaWithStates_0(4, 7, 18);
         return jjMoveStringLiteralDfa5_0(active0, 0x10000000L);
      case 116:
         if ((active0 & 0x8000000L) != 0L)
            return jjStartNfaWithStates_0(4, 27, 18);
         break;
      case 121:
         return jjMoveStringLiteralDfa5_0(active0, 0x20180001000L);
      default :
         break;
   }
   return jjStartNfa_0(3, active0, 0L);
}
static private int jjMoveStringLiteralDfa5_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(3, old0, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(4, active0, 0L);
      return 5;
   }
   switch(curChar)
   {
      case 68:
         return jjMoveStringLiteralDfa6_0(active0, 0x10000000L);
      case 69:
         return jjMoveStringLiteralDfa6_0(active0, 0x20000000000L);
      case 84:
         return jjMoveStringLiteralDfa6_0(active0, 0x100000000L);
      case 99:
         if ((active0 & 0x200L) != 0L)
            return jjStartNfaWithStates_0(5, 9, 18);
         else if ((active0 & 0x400L) != 0L)
            return jjStartNfaWithStates_0(5, 10, 18);
         return jjMoveStringLiteralDfa6_0(active0, 0x40000000L);
      case 100:
         return jjMoveStringLiteralDfa6_0(active0, 0x20000100L);
      case 101:
         if ((active0 & 0x2000L) != 0L)
            return jjStartNfaWithStates_0(5, 13, 18);
         break;
      case 103:
         if ((active0 & 0x1000000L) != 0L)
            return jjStartNfaWithStates_0(5, 24, 18);
         break;
      case 106:
         if ((active0 & 0x4000000000L) != 0L)
            return jjStartNfaWithStates_0(5, 38, 18);
         break;
      case 109:
         if ((active0 & 0x2000000L) != 0L)
            return jjStartNfaWithStates_0(5, 25, 18);
         break;
      case 110:
         if ((active0 & 0x100000L) != 0L)
            return jjStartNfaWithStates_0(5, 20, 18);
         else if ((active0 & 0x200000000L) != 0L)
            return jjStartNfaWithStates_0(5, 33, 18);
         break;
      case 112:
         return jjMoveStringLiteralDfa6_0(active0, 0x80001000L);
      case 114:
         return jjMoveStringLiteralDfa6_0(active0, 0x10000000000L);
      case 116:
         return jjMoveStringLiteralDfa6_0(active0, 0x400000000L);
      case 121:
         return jjMoveStringLiteralDfa6_0(active0, 0x4000L);
      default :
         break;
   }
   return jjStartNfa_0(4, active0, 0L);
}
static private int jjMoveStringLiteralDfa6_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(4, old0, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(5, active0, 0L);
      return 6;
   }
   switch(curChar)
   {
      case 68:
         return jjMoveStringLiteralDfa7_0(active0, 0x20000000L);
      case 97:
         return jjMoveStringLiteralDfa7_0(active0, 0x10000000000L);
      case 101:
         if ((active0 & 0x1000L) != 0L)
            return jjStartNfaWithStates_0(6, 12, 18);
         else if ((active0 & 0x80000000L) != 0L)
            return jjStartNfaWithStates_0(6, 31, 18);
         return jjMoveStringLiteralDfa7_0(active0, 0x10000000L);
      case 108:
         if ((active0 & 0x40000000L) != 0L)
            return jjStartNfaWithStates_0(6, 30, 18);
         return jjMoveStringLiteralDfa7_0(active0, 0x20000000000L);
      case 109:
         return jjMoveStringLiteralDfa7_0(active0, 0x400000000L);
      case 112:
         return jjMoveStringLiteralDfa7_0(active0, 0x4000L);
      case 115:
         if ((active0 & 0x100L) != 0L)
            return jjStartNfaWithStates_0(6, 8, 18);
         break;
      case 121:
         return jjMoveStringLiteralDfa7_0(active0, 0x100000000L);
      default :
         break;
   }
   return jjStartNfa_0(5, active0, 0L);
}
static private int jjMoveStringLiteralDfa7_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(5, old0, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(6, active0, 0L);
      return 7;
   }
   switch(curChar)
   {
      case 99:
         return jjMoveStringLiteralDfa8_0(active0, 0x10000000L);
      case 101:
         if ((active0 & 0x4000L) != 0L)
            return jjStartNfaWithStates_0(7, 14, 18);
         return jjMoveStringLiteralDfa8_0(active0, 0x20000000L);
      case 109:
         if ((active0 & 0x20000000000L) != 0L)
            return jjStartNfaWithStates_0(7, 41, 18);
         break;
      case 112:
         return jjMoveStringLiteralDfa8_0(active0, 0x100000000L);
      case 116:
         if ((active0 & 0x400000000L) != 0L)
            return jjStartNfaWithStates_0(7, 34, 18);
         break;
      case 121:
         if ((active0 & 0x10000000000L) != 0L)
            return jjStartNfaWithStates_0(7, 40, 18);
         break;
      default :
         break;
   }
   return jjStartNfa_0(6, active0, 0L);
}
static private int jjMoveStringLiteralDfa8_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(6, old0, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(7, active0, 0L);
      return 8;
   }
   switch(curChar)
   {
      case 99:
         return jjMoveStringLiteralDfa9_0(active0, 0x20000000L);
      case 101:
         if ((active0 & 0x100000000L) != 0L)
            return jjStartNfaWithStates_0(8, 32, 18);
         break;
      case 108:
         if ((active0 & 0x10000000L) != 0L)
            return jjStartNfaWithStates_0(8, 28, 18);
         break;
      default :
         break;
   }
   return jjStartNfa_0(7, active0, 0L);
}
static private int jjMoveStringLiteralDfa9_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(7, old0, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(8, active0, 0L);
      return 9;
   }
   switch(curChar)
   {
      case 108:
         if ((active0 & 0x20000000L) != 0L)
            return jjStartNfaWithStates_0(9, 29, 18);
         break;
      default :
         break;
   }
   return jjStartNfa_0(8, active0, 0L);
}
static private int jjStartNfaWithStates_0(int pos, int kind, int state)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) { return pos + 1; }
   return jjMoveNfa_0(state, pos + 1);
}
static final long[] jjbitVec0 = {
   0x0L, 0x0L, 0xffffffffffffffffL, 0xffffffffffffffffL
};
static private int jjMoveNfa_0(int startState, int curPos)
{
   int startsAt = 0;
   jjnewStateCnt = 19;
   int i = 1;
   jjstateSet[0] = startState;
   int kind = 0x7fffffff;
   for (;;)
   {
      if (++jjround == 0x7fffffff)
         ReInitRounds();
      if (curChar < 64)
      {
         long l = 1L << curChar;
         do
         {
            switch(jjstateSet[--i])
            {
               case 0:
                  if ((0x3ff000000000000L & l) != 0L)
                  {
                     if (kind > 43)
                        kind = 43;
                     jjCheckNAdd(5);
                  }
                  else if (curChar == 34)
                     jjCheckNAddTwoStates(15, 16);
                  else if (curChar == 35)
                     jjCheckNAddStates(0, 2);
                  break;
               case 1:
                  if ((0xffffffffffffdbffL & l) != 0L)
                     jjCheckNAddStates(0, 2);
                  break;
               case 2:
                  if ((0x2400L & l) != 0L && kind > 6)
                     kind = 6;
                  break;
               case 3:
                  if (curChar == 10 && kind > 6)
                     kind = 6;
                  break;
               case 4:
                  if (curChar == 13)
                     jjstateSet[jjnewStateCnt++] = 3;
                  break;
               case 5:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 43)
                     kind = 43;
                  jjCheckNAdd(5);
                  break;
               case 14:
                  if (curChar == 34)
                     jjCheckNAddTwoStates(15, 16);
                  break;
               case 15:
                  if ((0xfffffffbfffffbffL & l) != 0L)
                     jjCheckNAddTwoStates(15, 16);
                  break;
               case 16:
                  if (curChar == 34 && kind > 45)
                     kind = 45;
                  break;
               case 18:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 48)
                     kind = 48;
                  jjstateSet[jjnewStateCnt++] = 18;
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else if (curChar < 128)
      {
         long l = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 0:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                  {
                     if (kind > 48)
                        kind = 48;
                     jjCheckNAdd(18);
                  }
                  if (curChar == 102)
                     jjstateSet[jjnewStateCnt++] = 12;
                  else if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 8;
                  break;
               case 1:
                  jjAddStates(0, 2);
                  break;
               case 6:
                  if (curChar == 101 && kind > 44)
                     kind = 44;
                  break;
               case 7:
                  if (curChar == 117)
                     jjCheckNAdd(6);
                  break;
               case 8:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 7;
                  break;
               case 9:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 8;
                  break;
               case 10:
                  if (curChar == 115)
                     jjCheckNAdd(6);
                  break;
               case 11:
                  if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 10;
                  break;
               case 12:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 11;
                  break;
               case 13:
                  if (curChar == 102)
                     jjstateSet[jjnewStateCnt++] = 12;
                  break;
               case 15:
                  jjAddStates(3, 4);
                  break;
               case 17:
               case 18:
                  if ((0x7fffffe07fffffeL & l) == 0L)
                     break;
                  if (kind > 48)
                     kind = 48;
                  jjCheckNAdd(18);
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else
      {
         int i2 = (curChar & 0xff) >> 6;
         long l2 = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 1:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     jjAddStates(0, 2);
                  break;
               case 15:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     jjAddStates(3, 4);
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      if (kind != 0x7fffffff)
      {
         jjmatchedKind = kind;
         jjmatchedPos = curPos;
         kind = 0x7fffffff;
      }
      ++curPos;
      if ((i = jjnewStateCnt) == (startsAt = 19 - (jjnewStateCnt = startsAt)))
         return curPos;
      try { curChar = input_stream.readChar(); }
      catch(java.io.IOException e) { return curPos; }
   }
}
static final int[] jjnextStates = {
   1, 2, 4, 15, 16, 
};

/** Token literal values. */
public static final String[] jjstrLiteralImages = {
"", null, null, null, null, null, null, "\143\154\141\163\163", 
"\105\170\164\145\156\144\163", "\123\164\141\164\151\143", "\120\165\142\154\151\143", "\166\157\151\144", 
"\111\156\164\124\171\160\145", "\104\157\165\142\154\145", "\102\157\157\154\124\171\160\145", 
"\116\145\167", "\124\150\151\163", "\111\146", "\105\154\163\145", "\127\150\151\154\145", 
"\122\145\164\165\162\156", "\115\141\151\156", "\124\162\165\145", "\106\141\154\163\145", 
"\123\164\162\151\156\147", "\123\171\163\164\145\155", "\117\165\164", "\120\162\151\156\164", 
"\103\154\141\163\163\104\145\143\154", "\115\145\164\150\157\144\104\145\143\154", "\126\141\162\104\145\143\154", 
"\117\142\152\124\171\160\145", "\101\162\162\141\171\124\171\160\145", "\101\163\163\151\147\156", 
"\103\141\154\154\123\164\155\164", "\102\151\156\157\160", "\125\156\157\160", "\103\141\154\154", 
"\116\145\167\117\142\152", "\106\151\145\154\144", "\116\145\167\101\162\162\141\171", 
"\101\162\162\141\171\105\154\155", "\120\141\162\141\155", null, null, null, null, null, null, "\50", "\51", 
"\173", "\175", "\53", "\55", "\52", "\57", "\46\46", "\174\174", "\75\75", "\41\75", 
"\74", "\74\75", "\76", "\76\75", "\41", };

/** Lexer state names. */
public static final String[] lexStateNames = {
   "DEFAULT",
};
static final long[] jjtoToken = {
   0xffff3fffffffff81L, 0x3L, 
};
static final long[] jjtoSkip = {
   0x7eL, 0x0L, 
};
static protected SimpleCharStream input_stream;
static private final int[] jjrounds = new int[19];
static private final int[] jjstateSet = new int[38];
private static final StringBuilder jjimage = new StringBuilder();
private static StringBuilder image = jjimage;
private static int jjimageLen;
private static int lengthOfMatch;
static protected char curChar;
/** Constructor. */
public AstParserTokenManager(SimpleCharStream stream){
   if (input_stream != null)
      throw new TokenMgrError("ERROR: Second call to constructor of static lexer. You must use ReInit() to initialize the static variables.", TokenMgrError.STATIC_LEXER_ERROR);
   input_stream = stream;
}

/** Constructor. */
public AstParserTokenManager(SimpleCharStream stream, int lexState){
   this(stream);
   SwitchTo(lexState);
}

/** Reinitialise parser. */
static public void ReInit(SimpleCharStream stream)
{
   jjmatchedPos = jjnewStateCnt = 0;
   curLexState = defaultLexState;
   input_stream = stream;
   ReInitRounds();
}
static private void ReInitRounds()
{
   int i;
   jjround = 0x80000001;
   for (i = 19; i-- > 0;)
      jjrounds[i] = 0x80000000;
}

/** Reinitialise parser. */
static public void ReInit(SimpleCharStream stream, int lexState)
{
   ReInit(stream);
   SwitchTo(lexState);
}

/** Switch to specified lex state. */
static public void SwitchTo(int lexState)
{
   if (lexState >= 1 || lexState < 0)
      throw new TokenMgrError("Error: Ignoring invalid lexical state : " + lexState + ". State unchanged.", TokenMgrError.INVALID_LEXICAL_STATE);
   else
      curLexState = lexState;
}

static protected Token jjFillToken()
{
   final Token t;
   final String curTokenImage;
   final int beginLine;
   final int endLine;
   final int beginColumn;
   final int endColumn;
   String im = jjstrLiteralImages[jjmatchedKind];
   curTokenImage = (im == null) ? input_stream.GetImage() : im;
   beginLine = input_stream.getBeginLine();
   beginColumn = input_stream.getBeginColumn();
   endLine = input_stream.getEndLine();
   endColumn = input_stream.getEndColumn();
   t = Token.newToken(jjmatchedKind, curTokenImage);

   t.beginLine = beginLine;
   t.endLine = endLine;
   t.beginColumn = beginColumn;
   t.endColumn = endColumn;

   return t;
}

static int curLexState = 0;
static int defaultLexState = 0;
static int jjnewStateCnt;
static int jjround;
static int jjmatchedPos;
static int jjmatchedKind;

/** Get the next Token. */
public static Token getNextToken() 
{
  Token matchedToken;
  int curPos = 0;

  EOFLoop :
  for (;;)
  {
   try
   {
      curChar = input_stream.BeginToken();
   }
   catch(java.io.IOException e)
   {
      jjmatchedKind = 0;
      matchedToken = jjFillToken();
      return matchedToken;
   }
   image = jjimage;
   image.setLength(0);
   jjimageLen = 0;

   try { input_stream.backup(0);
      while (curChar <= 32 && (0x100003600L & (1L << curChar)) != 0L)
         curChar = input_stream.BeginToken();
   }
   catch (java.io.IOException e1) { continue EOFLoop; }
   jjmatchedKind = 0x7fffffff;
   jjmatchedPos = 0;
   curPos = jjMoveStringLiteralDfa0_0();
   if (jjmatchedKind != 0x7fffffff)
   {
      if (jjmatchedPos + 1 < curPos)
         input_stream.backup(curPos - jjmatchedPos - 1);
      if ((jjtoToken[jjmatchedKind >> 6] & (1L << (jjmatchedKind & 077))) != 0L)
      {
         matchedToken = jjFillToken();
         TokenLexicalActions(matchedToken);
         return matchedToken;
      }
      else
      {
         continue EOFLoop;
      }
   }
   int error_line = input_stream.getEndLine();
   int error_column = input_stream.getEndColumn();
   String error_after = null;
   boolean EOFSeen = false;
   try { input_stream.readChar(); input_stream.backup(1); }
   catch (java.io.IOException e1) {
      EOFSeen = true;
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
      if (curChar == '\n' || curChar == '\r') {
         error_line++;
         error_column = 0;
      }
      else
         error_column++;
   }
   if (!EOFSeen) {
      input_stream.backup(1);
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
   }
   throw new TokenMgrError(EOFSeen, curLexState, error_line, error_column, error_after, curChar, TokenMgrError.LEXICAL_ERROR);
  }
}

static void TokenLexicalActions(Token matchedToken)
{
   switch(jjmatchedKind)
   {
      case 43 :
        image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
    try {
      Integer.parseInt(matchedToken.image);
    } catch (Exception e) {
      throw new TokenMgrError("Lexical error at line " + matchedToken.beginLine +
                              ", column " + matchedToken.beginColumn +
                              ". Integer overflow: " + matchedToken.image, 0);
    }
         break;
      default :
         break;
   }
}
static private void jjCheckNAdd(int state)
{
   if (jjrounds[state] != jjround)
   {
      jjstateSet[jjnewStateCnt++] = state;
      jjrounds[state] = jjround;
   }
}
static private void jjAddStates(int start, int end)
{
   do {
      jjstateSet[jjnewStateCnt++] = jjnextStates[start];
   } while (start++ != end);
}
static private void jjCheckNAddTwoStates(int state1, int state2)
{
   jjCheckNAdd(state1);
   jjCheckNAdd(state2);
}

static private void jjCheckNAddStates(int start, int end)
{
   do {
      jjCheckNAdd(jjnextStates[start]);
   } while (start++ != end);
}

}
