/* Generated By:JavaCC: Do not edit this line. AstParserConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface AstParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int IntLit = 43;
  /** RegularExpression Id. */
  int BoolLit = 44;
  /** RegularExpression Id. */
  int StrLit = 45;
  /** RegularExpression Id. */
  int DIGIT = 46;
  /** RegularExpression Id. */
  int LETTER = 47;
  /** RegularExpression Id. */
  int Id = 48;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "<token of kind 6>",
    "\"class\"",
    "\"Extends\"",
    "\"Static\"",
    "\"Public\"",
    "\"void\"",
    "\"IntType\"",
    "\"Double\"",
    "\"BoolType\"",
    "\"New\"",
    "\"This\"",
    "\"If\"",
    "\"Else\"",
    "\"While\"",
    "\"Return\"",
    "\"Main\"",
    "\"True\"",
    "\"False\"",
    "\"String\"",
    "\"System\"",
    "\"Out\"",
    "\"Print\"",
    "\"ClassDecl\"",
    "\"MethodDecl\"",
    "\"VarDecl\"",
    "\"ObjType\"",
    "\"ArrayType\"",
    "\"Assign\"",
    "\"CallStmt\"",
    "\"Binop\"",
    "\"Unop\"",
    "\"Call\"",
    "\"NewObj\"",
    "\"Field\"",
    "\"NewArray\"",
    "\"ArrayElm\"",
    "\"Param\"",
    "<IntLit>",
    "<BoolLit>",
    "<StrLit>",
    "<DIGIT>",
    "<LETTER>",
    "<Id>",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"&&\"",
    "\"||\"",
    "\"==\"",
    "\"!=\"",
    "\"<\"",
    "\"<=\"",
    "\">\"",
    "\">=\"",
    "\"!\"",
  };

}
